# Generated by Django 5.0.3 on 2024-05-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0006_remove_orderdetail_product_product'),
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
